### ISSUE TITLE
Do not add libraries/frameworks not built by Carthage

### ISSUE THREAD

**Issue by virusman** [artemnovichkov/Carting#1]
I import StoreKit.framework as well as a couple of static libraries from other folders. Carting adds them as parameters to copy-frameworks script. Libraries and frameworks not sourced from Carthage build folder should be ignored.

**Comment by artemnovichkov** [comment]
Good remark! I removed check of Carthage folder, but it makes sense. Thank you for contributing, I will fix it next days.

**Comment by artemnovichkov** [comment]
Hi, @virusman! I have fixed the issue in [1.2.1](https://github.com/artemnovichkov/Carting/releases/tag/1.2.1) release. I checked it by myself, but it would be great if you check it in your project.

**Comment by virusman** [comment]
Yup, it works correctly now. Thanks!
