### ISSUE TITLE
🤷‍♂️ Nothing to update

### ISSUE THREAD

**Issue by evgenmikhaylov** [artemnovichkov/Carting#13]
When I run `carting update` in my project directory - I receive following message `🤷‍♂️ Nothing to update` and 'Carthage' run script wasn't added. 

Carting version:
1.2.11

My cartfile:
github "Otbivnoe/Deboogger"

My project:
workspace with 2 targets: 'project' and 'cocoa pods'

**Comment by artemnovichkov** [comment]
As @medvedzzz, he forgot to link the framework to `project` target. I'll close the issue. Thank you for contributing 👨🏻‍💻
