### ISSUE TITLE
Ignore frameworks

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/Carting#15]
Paths for debugging frameworks like [Hyperion-iOS](https://github.com/willowtreeapps/Hyperion-iOS) should not be added. So I need a simple approach to mark these frameworks for ignoring, for example in Cartfile:
`github "willowtreeapps/Hyperion-iOS" #carting.ignore`

**Comment by dstranz** [comment]
@artemnovichkov It is not that `Cartfile.private` should be used for the same reason? https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfileprivate

**Comment by artemnovichkov** [comment]
@dstranz, thanks for the link! I didn't know about this feature. Will try and maybe close the issue. But maybe you know other cases when Carting shouldn't add the paths?

**Comment by dstranz** [comment]
@artemnovichkov I will consider maybe adding new feature `--private` and that will add frameworks described in `Cartfile.private` to UI & Unit test targets (if it's possible to detect that from project files?).
