### ISSUE TITLE
Take a lot of time and failed if there is space in project folder

### ISSUE THREAD

**Issue by phimage** [artemnovichkov/Carting#17]
`carting update` or `carthage list` hang  if there is space in project folder

For `carthage list` I see in `FrameworkInformationService`
```swift
        let fileOutput = try shellOut(to: "file", arguments: [path])
        let lipoOutput = try shellOut(to: "lipo", arguments: ["-info", path])
```
By escaping path
```swift
        let fileOutput = try shellOut(to: "file", arguments: ["'\(path)'"])
        let lipoOutput = try shellOut(to: "lipo", arguments: ["-info", "'\(path)'"])
```
I have no more issue

If path must be escaped, a lot of `shellOut` must be edited
and I do not know If this could add new issues.

**Comment by artemnovichkov** [comment]
Hi, @phimage! Thank you for using Carting! I don't understand the problem. Could you explain it, please? I guess your changes are minor and will not break something.

**Comment by artemnovichkov** [comment]
Oh, I read the title. Could you please send a PR? I'll release a new version.

**Comment by phimage** [comment]
ok I will

Using an extension in `StringExtention`?

```swift
     var quotify: String {
           return "'\(self)'"
     }
```

**Comment by artemnovichkov** [comment]
Looks good!
