### ISSUE TITLE
Carting creates build phases with no parameters for test targets

### ISSUE THREAD

**Issue by virusman** [artemnovichkov/Carting#2]
I have 2 test targets in my project. Carting creates build phases with '/usr/local/bin/carthage copy-frameworks' and no parameters for these test targets. Is it by design? It seems like 9b4511c0721840ca451f423225b56b2d1041f111 was supposed to fix it, but it still generates empty calls for my test targets.

**Comment by artemnovichkov** [comment]
I didn't check it with test targets. `copy-frameworks` script without paths makes no sense. I'll check it, thank you again!

**Comment by artemnovichkov** [comment]
I'm trying to reproduce the issue, but test target looks good. Maybe I miss something?..
![screen shot 2017-07-24 at 21 30 41](https://user-images.githubusercontent.com/5051597/28531037-6722f0ec-70b7-11e7-891d-a3562b962855.png)

**Comment by artemnovichkov** [comment]
Hi, @virusman! I'll close the issue. Please, tell if you still have the error.
