### ISSUE TITLE
Paths for file lists

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/Carting#25]
Carting saves filelists to Carthage folder by default. But often this folder is in gitignore. Just think about paths or at least info in readme about this case.

**Comment by dstranz** [comment]
@artemnovichkov I've just check IMO the most popular [.gitignore for Xcode](https://github.com/github/gitignore/blob/master/Global/Xcode.gitignore) project and it includes the following lines:

```
# Carthage
#
# Add this line if you want to avoid checking in source code from Carthage dependencies.
# Carthage/Checkouts

Carthage/Build
```

So Carthage folder is not excluded in most common cases. And what's more important is it `xcfilelists` folder worth something without `Builds` folder?

On the other hand, maybe it's an option to use Carting directory as a default output?

**Comment by artemnovichkov** [comment]
Hi, @dstranz! Thanks for the suggestions! The main point is that Carting is not synced with Carthage. It leads to some problems: wrong paths, missing xcfilelists etc. The simplest way is to update README with this warning. I thought about using Carting as a proxy for Carthage commands with additional main logic. But... I don't like this idea. So now Carting users should think about path updates.

About folders - .gitignore is a good example of common cases. We should warn users about cases when Carthage folder is ignored by git. In my opinion, we should show a warning in Console and lead users to track xcfilelists. What do you think?

**Comment by dstranz** [comment]
@artemnovichkov We could use `git check-ignore Carthage/xcfilelists` on `Cartfile` start and then show warning if it is.

**Comment by artemnovichkov** [comment]
On Cartfile of Carting? Honestly I didn't know about `check-ignore` command

**Comment by dstranz** [comment]
Yeah, in Carting :) 

https://git-scm.com/docs/git-check-ignore
