### ISSUE TITLE
Carting is deleting custom build phases

### ISSUE THREAD

**Issue by olejnjak** [artemnovichkov/Carting#29]
Hi, since last update I am experiencing a problem, that everytime I run `carting update -f file` (it doesn't matter if I use file or list format), I end up with all custom build phases removed. 

I was trying to create a minimal project which has this issue but in clean project it worked just fine. Our [project template](https://github.com/AckeeCZ/iOS-MVVM-ProjectTemplate) has this issue.

Do you have an idea what might be the problem? The 1.2.15 version works just fine.

**Comment by artemnovichkov** [comment]
Hi, @olejnjak! At first thanks for using Carting! I'll try to reproduce this issue. It's definitely related to the new logic of xcfilelist support. Stay tuned, I'll fix it ASAP because it should be quite annoying.

**Comment by artemnovichkov** [comment]
@olejnjak  I've released 1.3.1 version with fix of the issue. I tested with your template. FYI, carting won't parse scripts without filelist paths. Please, check the new release and reopen the issue if you still reproduce it.
https://github.com/artemnovichkov/Carting/releases/tag/1.3.1

**Comment by olejnjak** [comment]
Yes, seems to work just fine 🙂

**Comment by artemnovichkov** [comment]
Perfect!
