### ISSUE TITLE
Exclude unit tests target from carting update action

### ISSUE THREAD

**Issue by alphatroya** [artemnovichkov/Carting#30]
When I launch `carting update` on my project it creates a new "Carthage" build phase for unit tests target too. The Carthage tutorial says that `copy-frameworks` action is not needed for unit tests and it's very annoyable to deleting this script each time. Or maybe I doing something wrong?

**Comment by artemnovichkov** [comment]
Hi, @alphatroya! Thanks for the issue! Yes, you're right. I saw this case. With current implementation, I can't check test targets properly. The best implementation is adding product types to targets. Unfortunately, it maps as a string now.

https://github.com/artemnovichkov/Carting/blob/6d83f1946f4a423bcbfca8e6b8f9532f5e2e777b/Sources/CartingCore/Models/TargetBody.swift#L17

**Comment by alphatroya** [comment]
Maybe it should be limited enum. That array that can be filtered by "com.apple.product-type.application" type automatically or manually by command line parameter?

**Comment by artemnovichkov** [comment]
I saw this logic in xcodeproj
https://github.com/tuist/xcodeproj/blob/fab570f365f874c5803d6a2ad8fc42a43e970446/Sources/xcodeproj/Objects/Targets/PBXProductType.swift#L4-L24
I guess we can use it or at least add two cases: `application` and `other`.

**Comment by alphatroya** [comment]
Ok, I'll try to submit my solution soon.

**Comment by artemnovichkov** [comment]
Cool, thank you!
