### ISSUE TITLE
Add flag to disable adding/updating the build script phase

### ISSUE THREAD

**Issue by rastersize** [artemnovichkov/Carting#34]
Hey @artemnovichkov!

I’m looking at using Carting for a project I’m working on. However I’d like to be able to have Carting only update the `xcfilelist`. This is because I don’t want or need any scripts to update the build phase. I’ve added it already for our current Carthage integration, it’s also a bit custom where we perform some additional work. So I need to keep maintain that manually.

What do you think about such an option to disable changing the Xcode project file? And just read the Xcode project and Carthage output to update the `xcfilelist`.
If you’re open to it I’d be willing to make the necessary changes.

**Comment by artemnovichkov** [comment]
Hi, @rastersize! Thanks for the feedback! I guess for your case Carting should work like:
```bash
carting update -s MyCustomScript --paths-only
```
You set a script name as a parameter and add a flag for updating only paths. It catches both cases - xcfilelists and input files. What do you think?

It would be great if you implement it 🙂

**Comment by rastersize** [comment]
@artemnovichkov Great! I’ll try to find some time this weekend for it 🙂

**Comment by artemnovichkov** [comment]
Hi, @rastersize! I know I'm too late, but did you use Carting >1.3.3 version? It should update only xcfilelists it the project was configured correctly.

**Comment by artemnovichkov** [comment]
I'll close the issue because it has not had recent activity. Feel free to open it again if there is still an issue for you.
