### ISSUE TITLE
"🤷‍♂️ Nothing to update", but the xcfilelists were updated

### ISSUE THREAD

**Issue by acecilia** [artemnovichkov/Carting#38]
I am using carting 1.3.2. After dragging new carthage frameworks to the project and adding them to the targets, I run `carting update` to update the build script. The xcfilelists are updated correctly, but carting returns "🤷‍♂️ Nothing to update.".

**Comment by artemnovichkov** [comment]
Thanks for the issue! As I remember carting checks only changes in project files. But I agree there should be proper messages for any updates. Current logic for it is trivial, I set a flag for any changes:
https://github.com/artemnovichkov/Carting/blob/394228d3caa47d92e92bc66d29a0b4016422bb9f/Sources/CartingCore/Services/FrameworkInformationService.swift#L145-L150
What's your suggestion? Another type of message? Of unify the common message?
https://github.com/artemnovichkov/Carting/blob/394228d3caa47d92e92bc66d29a0b4016422bb9f/Sources/CartingCore/Services/FrameworkInformationService.swift#L140

**Comment by acecilia** [comment]
I think the more information the tools outputs about the changes it is doing, the better. My proposal is:

1. `🤷‍♂️ Nothing to update.` when there are no changes to source control at all.
2. `✅ Script \(scriptName) was successfully added to \(target.name) target.` when a script phase was added to a target. This means that the `.pbxproj` file will appear as changed in source control.
3. `✅ xcfilelist file \(xcfilelistFileName) was updated.` when the script phase is already there, but a xcfilelist was updated to include a new linked framework. This means that the xcfilelist files will appear as changed in source control.

This way the user can look at source control, and relate the changes happening there to what `carting` said that was changed.

**Comment by artemnovichkov** [comment]
Hi, @acecilia! Sorry got the long time update. I hope you're still using Carting. Could you please check [the last update](https://github.com/artemnovichkov/Carting/releases/tag/1.3.6)? I've fixed messaging.

**Comment by artemnovichkov** [comment]
I'll close the issue because it has not had recent activity. Feel free to open it again if there is still an issue for you.
