### ISSUE TITLE
Installation fails with error - @rpath/llbuild.framework/Versions/A/llbuild Library not loaded, reason - image not found

### ISSUE THREAD

**Issue by kedarchiselcut** [artemnovichkov/Carting#43]
==> Installing carting from artemnovichkov/projects
==> Downloading https://github.com/artemnovichkov/Carting/archive/1.3.5.tar.gz
==> Downloading from https://codeload.github.com/artemnovichkov/Carting/tar.gz/1.3.5
######################################################################## 100.0%
==> make install PREFIX=/usr/local/Cellar/carting/1.3.5
Last 15 lines from /Users/jombay/Library/Logs/Homebrew/carting/01.make:
2019-04-23 12:17:29 +0530

make
install
PREFIX=/usr/local/Cellar/carting/1.3.5

swift build --disable-sandbox -c release
dyld: Library not loaded: @rpath/llbuild.framework/Versions/A/llbuild
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/swift-build
  Reason: image not found
make: *** [build] Abort trap: 6

**Comment by artemnovichkov** [comment]
Hi, @kedarchiselcut! Thanks for the info! Which Xcode do you use?

**Comment by kedarchiselcut** [comment]
Hey,
Thanks for the quick reply. I am using Xcode Version 10.2.1. MacOS 10.14.4.

--

Thanks,
Kedar.

**Comment by artemnovichkov** [comment]
Try to run:
```bash
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by kedarchiselcut** [comment]
Thanks! That seems to resolve the issue. What was I missing here? What was the cause of this error?

**Comment by artemnovichkov** [comment]
Glad to know! I found the solution [here](https://stackoverflow.com/questions/55432373/unable-to-run-swift-package-manager-macos-10-14-4).

**Comment by kedarchiselcut** [comment]
Thanks a lot!

**Comment by Appsorwebs** [comment]
> Try to run:
> 
> ```shell
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
> ```

Worked but I got this error this time  after running your code.    
swift package init --type executable
Creating executable package: lib
Creating Package.swift
error: unknownOSError
