### ISSUE TITLE
Secondary dependencies are missing in copy frameworks phase

### ISSUE THREAD

**Issue by kokluch** [artemnovichkov/Carting#46]
After using Carting on a pretty big project I notice that many dependencies are missing. Mostly the indirect dependencies (dependencies of my dependencies) are not added to the copy frameworks phase. Looks like a major issue leading to an unusable tool. Any one having the same issue? Am I missing something?

**Comment by artemnovichkov** [comment]
As I remember, you should add all dependencies to the project even cycle dependencies. For instance, if you use [AlamofireObjectMapper](https://github.com/tristanhimmelman/AlamofireObjectMapper), you should add Alamofire and ObjectMapper to Linked Frameworks and Libraries section, right? In this case, they will be added to Carthage phase. Do you have static frameworks? Could you please share your Cartfile?

**Comment by kokluch** [comment]
My Cartfile is mostly private frameworks. I do have all of them in Linked Frameworks and Libraries. I 
 don't have any static frameworks. Actually it looks random. I have direct library requirement in my Cartfile which doesn't end up in the input file list. I have twice much more listed libraries using carting info than using carting update

**Comment by artemnovichkov** [comment]
It looks... strange! Have you tried to use `file` format?
