### ISSUE TITLE
Image not found error while installing Carting using Homebrew or manually 

### ISSUE THREAD

**Issue by real1900** [artemnovichkov/Carting#53]
Sulemans-MacBook-Pro-2:Documents sulemanimdad$ cd Carting
Sulemans-MacBook-Pro-2:Carting sulemanimdad$ make
swift build --disable-sandbox -c release
dyld: Library not loaded: @rpath/llbuild.framework/Versions/A/llbuild
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/swift-build
  Reason: image not found

**Comment by artemnovichkov** [comment]
Hi, @real1900! Could you lease check https://github.com/artemnovichkov/Carting/issues/43 issue?
