### ISSUE TITLE
add multiple project/workspace support in the same folder

### ISSUE THREAD

**Issue by ademozgur** [artemnovichkov/Carting#55]

**Comment by artemnovichkov** [comment]
Hi, @ademozgur! Thanks for the suggestion. Now Carting works only with first project in project folder.
https://github.com/artemnovichkov/Carting/blob/7705984f4ab5871158291549375910998f75ba4b/Sources/CartingCore/Services/ProjectService.swift#L237
I guess a new option with project name will be useful as well. What do you think?

**Comment by ademozgur** [comment]
there are possibilities like `--all` or `--only:project1,project2`. The default behavior might be --all option.

**Comment by artemnovichkov** [comment]
Hi, @ademozgur! I've released 2.1 version. Could you please check it?

**Comment by ademozgur** [comment]
Hi @artemnovichkov, i have tested the implementation, if I don't pass any project names with -n option, it does not update anything. If I pass all project names it works fine like this:

`carting update -n CartingTest1 CartingTest2`

**Comment by artemnovichkov** [comment]
And here is 2.1.1.  I forgot to check this case. Could you please check it again?

**Comment by ademozgur** [comment]
2.1.1 works fine, thanks for the implementation.
