### ISSUE TITLE
Empty xcfilelists

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/Carting#56]
When you run Carting for the first time, it logs:
`✅ Script Carthage in target Lifechronicle was successfully updated.`
There is a new script and "xcfilelists" folder. But there are no xcfilelists.

**Comment by innocarpe** [comment]
@artemnovichkov Hi, Would you release a new version including this? I saw the latest release is 2.1 (which doesn't include this 😂)

**Comment by innocarpe** [comment]
I tested in 2.1.1, and it generates empty xfilelists. 'Carthage script' is successfully updated. (only xfilelists has problems)

My project is based on `XcodeGen`, and it has multi targets(frameworks) like this. Do you have any idea to solve this issue? 🤔 

```
Carthage
Pods
Projects
  - SomeApplication
     - Resources
     - Sources
     - Supporting Files 
     - Tests
  - AATest
      - Sources
      - Tests
  - AAFoundation
      - Sources
      - Tests
```

**Comment by artemnovichkov** [comment]
Hi, @innocarpe, that's for the comments! I had no issue in last releases. I'll try to investigate it and fix. Feel free to clone Carting and debug it in your specific case, it would be great!
