### ISSUE TITLE
Failed to build carting 2.1.4 with SPM

### ISSUE THREAD

**Issue by alexanderpuchta** [artemnovichkov/Carting#63]
### Environment
Carting version: 1.3.2
macOS version: 10.15.7
Xcode version: 12.1
Installed via (mint, brew): brew + mint
What did you do?
#### Mint
> mint run artemnovichkov/carting
#### Brew
> brew tap artemnovichkov/projects
> brew install carting

### What did you expect to happen?
successful installation of Carting

#### Mint
🌱 Finding latest version of carting
🌱 Cloning carting 2.1.4
🌱 Resolving package
🌱 Building package
'Carting' /private/var/folders/cw/zks9qq_527l82gdr79kyl_zm0000gn/T/mint/github.com_artemnovichkov_carting: warning: ignoring duplicate product 'Carting'
'XcodeProj' /private/var/folders/cw/zks9qq_527l82gdr79kyl_zm0000gn/T/mint/github.com_artemnovichkov_carting/.build/checkouts/xcodeproj: error: Source files for target XcodeProj should be located under 'Sources/XcodeProj', or a custom sources path can be set with the 'path' property in Package.swift
🌱 Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.15". Use --verbose to see full output

#### Brew
==> Installing carting from artemnovichkov/projects
==> Downloading https://github.com/artemnovichkov/Carting/archive/2.1.4.tar.gz
==> Downloading from https://codeload.github.com/artemnovichkov/Carting/tar.gz/2.1.4
#=#=#                                                                         
==> make install PREFIX=/usr/local/Cellar/carting/2.1.4
Last 15 lines from /Users/alexanderpuchta/Library/Logs/Homebrew/carting/01.make:
Cloning https://github.com/kylef/PathKit
Resolving https://github.com/kylef/PathKit at 1.0.0
Cloning https://github.com/apple/swift-argument-parser
Resolving https://github.com/apple/swift-argument-parser at 0.0.1
Cloning https://github.com/tadija/AEXML
Resolving https://github.com/tadija/AEXML at 4.4.0
Cloning https://github.com/JohnSundell/ShellOut.git
Resolving https://github.com/JohnSundell/ShellOut.git at 2.2.0
Cloning https://github.com/tuist/xcodeproj.git
Resolving https://github.com/tuist/xcodeproj.git at 7.0.1
Cloning https://github.com/JohnSundell/Files.git
Resolving https://github.com/JohnSundell/Files.git at 3.1.0
'Carting' /private/tmp/carting-20201109-11556-urgg2r/Carting-2.1.4: warning: ignoring duplicate product 'Carting'
'XcodeProj' /private/tmp/carting-20201109-11556-urgg2r/Carting-2.1.4/.build/checkouts/xcodeproj: error: Source files for target XcodeProj should be located under 'Sources/XcodeProj', or a custom sources path can be set with the 'path' property in Package.swift
make: *** [build] Error 1

**Comment by artemnovichkov** [comment]
Hi, @alexanderpuchta! Thanks for the issue! It looks strange, but everything works on my machine with Xcode 12.1. Could you please try to update Package.swift with new xcodeproj version?
```swift
.package(url: "https://github.com/tuist/xcodeproj.git", .upToNextMajor(from: "7.17.0"))
```

**Comment by alexanderpuchta** [comment]
Thanks for this fast response @artemnovichkov. i've got this issue 5 days ago at another repo. the owner gave this information:

`It seems like the dependency XcodeProj which is used by SwiftKit fails to build due to an updated requirement of SPM that the name of a Swift Package must match the directory name inside the Sources directory.`

he change this, pushed a new version of this build, an all worked fine. maybe you can do this? :)

**Comment by artemnovichkov** [comment]
Could you please send me a link to this repo?

**Comment by artemnovichkov** [comment]
I've released 2.1.5 version. Could you please check it?

**Comment by alexanderpuchta** [comment]
great job! it's working now :-) thanks alot!

**Comment by artemnovichkov** [comment]
You're welcome!
