### ISSUE TITLE
[Feature Request] Add support for Application Extensions

### ISSUE THREAD

**Issue by RustyKnight** [artemnovichkov/Carting#64]
I have a "Notification Service" Application Extension in my project, which is sharing some code between the main project and the extension, these have some overlapping framework dependencies, but Carting does not update the extension :(

Support for these types of extensions would be really, really, awesome as the tool is an absolute life saver in large projects

**Comment by artemnovichkov** [comment]
Hi, @RustyKnight! Thank you for the feedback, I really appreciate it! According to this logic, Carting works only with application type targets, but it can be extend easily with new [types](https://github.com/tuist/XcodeProj/blob/0d4cab8fdb9a9a15bec066ce181e99675e0f2b2c/Sources/XcodeProj/Objects/Targets/PBXProductType.swift#L3) from XcodeProj. It would be great if you send a PR and check new logic for your project.
https://github.com/artemnovichkov/Carting/blob/113cedd5565d238389c54d58de2e4554b1bf3ae4/Sources/CartingCore/Services/ProjectService.swift#L244-L252

**Comment by artemnovichkov** [comment]
[Here](https://github.com/artemnovichkov/Carting/releases/tag/2.1.6) we go!
